# This file is only used for vulnerability alerts, not for automatic updates.
# This is due to the fact that Renovate does not support patching lock files directly.
# cf. https://docs.renovatebot.com/configuration-options/#transitiveremediation

version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # only allow vulnerabilities
    groups:
      python-vulnerabilities:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - "type: security"
    reviewers:
      - alma/squad-pre-purchase
      - alma/it-and-security-operation
