# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        name: Check commit message format
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]


  - repo: local
    hooks:
      - id: coding-standard-fixer
        name: PHP and Prestashop coding standards Fixer test
        language: system
        pass_filenames: false
        entry:  task lint:fix
        stages: [commit]

      - id: coding-standard
        name: Check the PHP and Prestashop coding standards
        language: system
        pass_filenames: false
        entry:  task lint
        stages: [commit]

      - id: php-compatibility
        name: Check the PHP compatibility
        language: system
        pass_filenames: false
        entry:  task php-compatibility
        stages: [commit]

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.91.0
    hooks:
      - id: semgrep
        args:
          - --error
          - --config
          - semgrep/rules/
          - --metrics
          - "off"
          - --quiet
          - --disable-version-check
          - --skip-unknown-extensions
        pass_filenames: false # Passing files explicitely override semgremignore

  - repo: https://github.com/alma/pre-commit-hooks
    rev: 1.1.2
    hooks:
      - id: check-branch-name
        args:
          - "-r^((chore|ci|dependabot|devx|docs|feature|fix|release|hotfix|hotfix-backport|infra|other|perf|refactor|security|test)\/.+|(snyk)-.+|main|develop|HEAD)$$"
