# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: coding-standard-fixer
        name: PHP and Prestashop coding standards Fixer test
        language: script
        # Replace by task lint:fix once PR https://github.com/alma/alma-installments-prestashop/pull/393 merged
        # Then remove ./scripts/coding-standard-fixer.sh
        entry:  ./scripts/coding-standard-fixer.sh
        stages: [commit]

      - id: coding-standard
        name: Check the PHP and Prestashop coding standards
        language: script
        # Replace by task lint:fix once PR https://github.com/alma/alma-installments-prestashop/pull/393 merged
        # Then remove ./scripts/coding-standard.sh
        entry:  ./scripts/coding-standard.sh
        stages: [commit]

      - id: php-compatibility
        name: Check the PHP compatibility
        language: script
        # Replace by task php-compatibililty once PR https://github.com/alma/alma-installments-prestashop/pull/393 merged
        # Then remove ./scripts/php-compatibility.sh
        entry:  ./scripts/php-compatibility.sh
        stages: [commit]

      #TODO : add task index:autoindex & task index:remove-blank-line once PR https://github.com/alma/alma-installments-prestashop/pull/393 merged
      #TODO : Add a script to checks that any new variables in smarty templates use |escape:'htmlall':'UTF-8' and print warning if not

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.27.0
    hooks:
      - id: semgrep
        args:
          - --error
          - --config
          - semgrep/rules/
          - --metrics
          - "off"
          - --quiet
          - --disable-version-check
          - --skip-unknown-extensions
        pass_filenames: false # Passing files explicitely override semgremignore

  - repo: https://github.com/alma/pre-commit-hooks
    rev: 1.1.2
    hooks:
      - id: check-branch-name
        args:
          - "-r^((chore|ci|dependabot|devx|docs|feature|fix|hotfix|hotfix-backport|infra|other|perf|refactor|security|test)\/.+|(snyk)-.+|main|develop|HEAD)$$"
