version: '3'

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
    expose:
      - 3306
    ports:
      - 3307:3306
    volumes:
      - "./tmp/db_data:/var/lib/mysql"

  prestashop:
    build:
      context: .
      args:
        # We are not using version 8.x for now, as this will install with PHP 8.x.
        # This will then require a PHPUnit version that will be too high, requiring
        # updating prestashop/autoindex.
        PLATFORM_VERSION: 1.7.8.7
    environment:
      - DB_SERVER=mysql
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWD=admin
      - PS_DEV_MODE=1
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=1
      - PS_INSTALL_DB=1
      - PS_DOMAIN=localhost:8080
      - PS_SHOP_URL=localhost:8080
      - PS_COUNTRY=FR
      - PS_LANGUAGE=fr
      - PS_FOLDER_ADMIN=almin
      - PS_FOLDER_INSTALL=alminstall
      - ADMIN_MAIL=admin@test.prestashop.com
      - ADMIN_PASSWD=test2test
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./alma:/var/www/html/modules/alma
      - /var/www/html/modules/alma/vendor # do not mount vendor inside container
      - ./docker/php-customization.ini:/usr/local/etc/php/conf.d/php-customization.ini
