version: 3

tasks:
  default:
    silent: true
    cmds:
      - task -l

  brew:
    preconditions:
      - sh: brew -v
        msg: 'This task requires `brew`. Please refer to this documentation: https://brew.sh/'

  pre-commit:
    desc: Install pre-commit tool
    internal: true
    deps: [brew]
    status:
      - pre-commit --version
    cmds:
      - brew install pre-commit

  pre-commit:install:
    desc: Install and set up pre-commit hooks
    deps: [pre-commit]
    cmds:
      - pre-commit install --hook-type pre-commit --hook-type commit-msg

  dist:
    desc: Build the zip file of the module
    cmds:
      - docker build -t alma_prestashop_builder:latest scripts/build/
      - docker run --rm -u $(id -u):$(id -g) -w ${PWD} -v "${PWD}:${PWD}" alma_prestashop_builder:latest /bin/sh scripts/build/build-dist-docker.sh
