alma_settings:
  path: /alma/settings
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\Alma\Infrastructure\Controller\SettingsController::indexAction'
    _legacy_controller: 'AdminAlmaSettings'
    _legacy_link: 'AdminAlmaSettings'
