alma_settings:
  path: /alma/settings
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Alma\Infrastructure\Controller\SettingsController::indexAction'
    _legacy_controller: 'AdminAlmaSettings'
