services:
  _defaults:
    public: true

  #####################
  # PrestaShop Account
  alma.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.3'

  alma.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@alma.ps_accounts_installer'

  ##############
  # Alma

  # Controllers


  # Services
  alma.module:
    class: Alma
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'alma'

  alma.context:
    class: Context
    factory: [ 'Context', 'getContext' ]

  alma.db:
    class: Db
    factory: [ 'Db', 'getInstance' ]

  alma.helper_form:
    class: HelperForm

  alma.php_encryption:
    class: PhpEncryption
    arguments:
      - !php/const _NEW_COOKIE_KEY_

  alma.form_builder:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\FormBuilder'
    arguments:
      - '@alma.input_form_builder'

  alma.input_form_builder:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\InputFormBuilder'

  alma.api_admin_form:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\ApiAdminForm'
    arguments:
      - '@alma.form_builder'

  alma.language_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\LanguageRepository'

  alma.settings_collection_form:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\SettingsCollectionForm'

  alma.ps_accounts_service:
    class: 'PrestaShop\Module\Alma\Application\Service\PsAccountsService'
    arguments:
      - '@alma.ps_accounts_facade'
      - '@alma.ps_accounts_installer'

  alma.module_service:
    class: 'PrestaShop\Module\Alma\Application\Service\ModuleService'
    arguments:
      - '@alma.module'
      - '@alma.language_repository'

  alma.module_installer_service:
    class: 'PrestaShop\Module\Alma\Application\Service\ModuleInstallerService'
    arguments:
      - '@alma.module_service'
      - '@alma.db'
      - '@alma.ps_accounts_installer'

  alma.settings_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\SettingsRepository'
    arguments:
      - '@alma.configuration_repository'
      - '@alma.tools_proxy'
      - '@alma.encryption_helper'

  alma.configuration_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\ConfigurationRepository'

  alma.tools_proxy:
    class: 'PrestaShop\Module\Alma\Infrastructure\Proxy\ToolsProxy'

  alma.settings_service:
    class: 'PrestaShop\Module\Alma\Application\Service\SettingsService'
    arguments:
      - '@alma.authentication_service'
      - '@alma.settings_repository'
      - '@alma.configuration_repository'
      - '@alma.tools_proxy'

  alma.settings_form_builder:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\SettingsFormBuilder'
    arguments:
      - '@alma.module'
      - '@alma.helper_form'
      - '@alma.settings_service'

  alma.encryption_helper:
    class: 'PrestaShop\Module\Alma\Application\Helper\EncryptionHelper'
    arguments:
      - '@alma.php_encryption'

  alma.authentication_service:
    class: 'PrestaShop\Module\Alma\Application\Service\AuthenticationService'
    arguments:
      - '@alma.settings_provider'
      - '@alma.merchant_endpoint'
      - '@alma.curl_client_factory'

  alma.client_configuration:
    class: 'Alma\Client\Application\ClientConfiguration'
    factory: ['@alma.client_configuration_factory', 'create']

  alma.client_configuration_factory:
    class: 'PrestaShop\Module\Alma\Infrastructure\Factory\ClientConfigurationFactory'
    arguments:
      - '@alma.settings_provider'
      - '@alma.environment'

  alma.curl_client:
    class: 'Alma\Client\Application\CurlClient'
    arguments:
      - '@alma.client_configuration'

  alma.merchant_endpoint:
    class: 'Alma\Client\Application\Endpoint\MerchantEndpoint'
    arguments:
      - '@alma.curl_client'

  alma.environment_factory:
    class: 'PrestaShop\Module\Alma\Infrastructure\Factory\EnvironmentFactory'
    arguments:
      - '@alma.settings_provider'

  alma.curl_client_factory:
    class: 'PrestaShop\Module\Alma\Infrastructure\Factory\CurlClientFactory'

  alma.settings_provider:
    class: 'PrestaShop\Module\Alma\Application\Provider\SettingsProvider'
    arguments:
      - '@alma.module'
      - '@alma.settings_repository'
      - '@alma.tools_proxy'

  alma.environment:
    class: 'Alma\Client\Domain\ValueObject\Environment'
    factory: ['@alma.environment_factory', 'create']
