services:
  _defaults:
    public: true

  #####################
  # PrestaShop Account
  alma.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.3'

  alma.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@alma.ps_accounts_installer'

  ##############
  # Alma

  # Controllers


  # Services
  alma.module:
    class: Alma
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'alma'

  alma.context:
    class: Context
    factory: [ 'Context', 'getContext' ]

  alma.db:
    class: Db
    factory: [ 'Db', 'getInstance' ]

  alma.helper_form:
    class: HelperForm

  alma.form_builder:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\FormBuilder'

  alma.input_form_builder:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\InputFormBuilder'

  alma.api_admin_form:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\ApiAdminForm'
    arguments:
      - '@alma.form_builder'
      - '@alma.input_form_builder'

  alma.language_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\LanguageRepository'

  alma.ps_accounts_service:
    class: 'PrestaShop\Module\Alma\Application\Service\PsAccountsService'
    arguments:
      - '@alma.ps_accounts_facade'
      - '@alma.ps_accounts_installer'

  alma.module_service:
    class: 'PrestaShop\Module\Alma\Application\Service\ModuleService'
    arguments:
      - '@alma.module'
      - '@alma.language_repository'

  alma.module_installer_service:
    class: 'PrestaShop\Module\Alma\Application\Service\ModuleInstallerService'
    arguments:
      - '@alma.module_service'
      - '@alma.db'
      - '@alma.ps_accounts_installer'

  alma.settings_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\SettingsRepository'
    arguments:
      - '@alma.configuration_repository'
      - '@alma.tools_repository'

  alma.configuration_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\ConfigurationRepository'

  alma.tools_repository:
    class: 'PrestaShop\Module\Alma\Infrastructure\Repository\ToolsRepository'

  alma.settings_service:
    class: 'PrestaShop\Module\Alma\Application\Service\SettingsService'
    arguments:
      - '@alma.module'
      - '@alma.settings_form_builder'
      - '@alma.settings_repository'
      - '@alma.tools_repository'

  alma.settings_form_builder:
    class: 'PrestaShop\Module\Alma\Infrastructure\Form\SettingsFormBuilder'
    arguments:
      - '@alma.module'
      - '@alma.helper_form'
      - '@alma.settings_repository'
      - '@alma.tools_repository'
      - '@alma.configuration_repository'
