<?php

namespace PrestaShop\Module\Alma\Tests\Unit\Infrastructure\Form;

use PHPUnit\Framework\TestCase;
use PrestaShop\Module\Alma\Infrastructure\Form\InputFormBuilder;

class InputFormBuilderTest extends TestCase
{
    /**
     * @var \PrestaShop\Module\Alma\Infrastructure\Form\InputFormBuilder
     */
    private InputFormBuilder $inputFormBuilder;

    public function setUp(): void
    {
        $this->inputFormBuilder = new InputFormBuilder();
    }

    public function testBuildInputText()
    {
        $expectInputText = [
            'type' => 'text',
            'label' => 'Api Key',
            'name' => 'ALMA_API_KEY',
            'size' => 20,
            'required' => true,
        ];
        $result = $this->inputFormBuilder->build(
            'text',
            'ALMA_API_KEY',
            'Api Key'
        );
        $this->assertEquals($expectInputText, $result);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
