<?php

namespace PrestaShop\Module\Alma\Tests\Unit\Infrastructure\Repository;

use PHPUnit\Framework\TestCase;
use PrestaShop\Module\Alma\Infrastructure\Repository\OrderStateRepository;

class OrderStateRepositoryTest extends TestCase
{
    public function setUp(): void
    {
        $this->context = $this->createMock(\Context::class);
        $this->language = $this->createMock(\Language::class);
        $this->language->id = 1;
        $this->context->language = $this->language;
        $this->orderStateRepository = new OrderStateRepository($this->context);
    }

    public function testGetAllOrderStates(): void
    {
        $orderStates = [
            [
                'id_order_state' => '17',
                'invoice' => '0',
                'send_email' => '0',
                'module_name' => 'ps_checkout',
                'color' => '#3498D8',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Authorized. To be captured by merchant',
                'template' => '',
            ],
            [
                'id_order_state' => '10',
                'invoice' => '0',
                'send_email' => '1',
                'module_name' => 'ps_wirepayment',
                'color' => '#34209E',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Awaiting bank wire payment',
                'template' => 'bankwire',
            ],
            [
                'id_order_state' => '13',
                'invoice' => '0',
                'send_email' => '0',
                'module_name' => 'ps_cashondelivery',
                'color' => '#34209E',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Awaiting Cash On Delivery validation',
                'template' => 'cashondelivery',
            ],
            [
                'id_order_state' => '1',
                'invoice' => '0',
                'send_email' => '1',
                'module_name' => 'ps_checkpayment',
                'color' => '#34209E',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Awaiting check payment',
                'template' => 'cheque',
            ],
            [
                'id_order_state' => '6',
                'invoice' => '0',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#2C3E50',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Canceled',
                'template' => 'order_canceled',
            ],
            [
                'id_order_state' => '5',
                'invoice' => '1',
                'send_email' => '0',
                'module_name' => '',
                'color' => '#01B887',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '1',
                'delivery' => '1',
                'shipped' => '1',
                'paid' => '1',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Delivered',
                'template' => '',
            ],
            [
                'id_order_state' => '12',
                'invoice' => '0',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#34209E',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'On backorder (not paid)',
                'template' => 'outofstock',
            ],
            [
                'id_order_state' => '9',
                'invoice' => '1',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#3498D8',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '1',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'On backorder (paid)',
                'template' => 'outofstock',
            ],
            [
                'id_order_state' => '16',
                'invoice' => '0',
                'send_email' => '0',
                'module_name' => 'ps_checkout',
                'color' => '#3498D8',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Partial payment',
                'template' => '',
            ],
            [
                'id_order_state' => '15',
                'invoice' => '0',
                'send_email' => '0',
                'module_name' => 'ps_checkout',
                'color' => '#01B887',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Partial refund',
                'template' => '',
            ],
            [
                'id_order_state' => '2',
                'invoice' => '1',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#3498D8',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '1',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '1',
                'pdf_invoice' => '1',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Payment accepted',
                'template' => 'payment',
            ],
            [
                'id_order_state' => '8',
                'invoice' => '0',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#E74C3C',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Payment error',
                'template' => 'payment_error',
            ],
            [
                'id_order_state' => '3',
                'invoice' => '1',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#3498D8',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '1',
                'delivery' => '1',
                'shipped' => '0',
                'paid' => '1',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Processing in progress',
                'template' => 'preparation',
            ],
            [
                'id_order_state' => '7',
                'invoice' => '1',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#01B887',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Refunded',
                'template' => 'refund',
            ],
            [
                'id_order_state' => '11',
                'invoice' => '1',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#3498D8',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '1',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '1',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Remote payment accepted',
                'template' => 'payment',
            ],
            [
                'id_order_state' => '4',
                'invoice' => '1',
                'send_email' => '1',
                'module_name' => '',
                'color' => '#01B887',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '1',
                'delivery' => '1',
                'shipped' => '1',
                'paid' => '1',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Shipped',
                'template' => 'shipped',
            ],
            [
                'id_order_state' => '14',
                'invoice' => '0',
                'send_email' => '0',
                'module_name' => 'ps_checkout',
                'color' => '#34209E',
                'unremovable' => '1',
                'hidden' => '0',
                'logable' => '0',
                'delivery' => '0',
                'shipped' => '0',
                'paid' => '0',
                'pdf_invoice' => '0',
                'pdf_delivery' => '0',
                'deleted' => '0',
                'id_lang' => '1',
                'name' => 'Waiting for payment',
                'template' => '',
            ],
        ];

        $this->assertEquals($orderStates, $this->orderStateRepository->getOrderStates());
    }
}
