watch:
  directories:
    - src
    - tests
  exclude:
    - vendor
  fileMask: '*.php'
  ignoreDotFiles: true
  ignoreVCS: true
  ignoreVCSIgnored: false
phpunit:
  binaryPath: vendor/bin/phpunit
  arguments: '-c phpunit.ci.xml'
