name: Aqua

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  aqua:
    name: Aqua scanner
    uses: alma/actions/.github/workflows/aqua.yml@v3
    secrets: inherit
    with:
      service-account: github-gar-alma-installments-p@lyrical-carver-335213.iam.gserviceaccount.com
