name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  lint-and-test:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install taskfile.dev
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker images
      uses: docker/bake-action@v4
      with:
        files: compose.yml
        pull: true
        load: true
        targets: |
          prestashop
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha

    - name: Run linter
      run: task lint:ci

    - name: Run unit Tests and Coverage
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'hotfix') }}
      run: task test
      env:
        XDEBUG_MODE: coverage
