name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  lint-and-test:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install taskfile.dev
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: 3.14

    - name: Run linter
      run: task lint:ci

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

    - name: Build docker images
      uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6.9.0
      with:
        files: compose.yml
        pull: true
        load: true
        targets: |
          prestashop
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha

    - name: Run unit Tests and Coverage
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'hotfix') }}
      run: task test
      env:
        XDEBUG_MODE: coverage

    - name: Install semgrep
      run: pip install semgrep

    - name: Run semgrep
      run: semgrep scan --config semgrep/rules
