name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:

  lint-and-test:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install taskfile.dev
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Run linter
      run: task ci:lint

    - name: Run unit Tests and Coverage
      run: task coverage
      env:
        XDEBUG_MODE: coverage
