name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  lint-and-test:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install taskfile.dev
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker images
      uses: docker/bake-action@v6
      with:
        files: compose.yml
        pull: true
        load: true
        targets: |
          prestashop
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha

    - name: Run unit Tests and Coverage
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'hotfix') }}
      run: task test
      env:
        XDEBUG_MODE: coverage

    - name: Build linter image
      run: task lint:build

    - name: Authenticating to Artifact Registry
      uses: "docker/login-action@v3"
      with:
        registry: "${{ env.REGISTRY_NAME }}"
        username: "oauth2accesstoken"
        password: "${{ steps.gcloud-auth.outputs.access_token }}"

    - name: Publish the Docker image to Google Artifact Registry
      run: |
        docker push "lint:ps"

    - name: Run linter
      run: task lint:ci

    - name: Install semgrep
      run: pip install semgrep

    - name: Run semgrep
      run: semgrep scan --config semgrep/rules
