---
name: E2E Test
on:
  pull_request:
    branches: ["main", "develop"]
    types: ["opened", "synchronize", "reopened",  "ready_for_review"]
  workflow_dispatch:

jobs:
  launch:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        version:
          - 1.7.8.7
          #- 1.7.7.5

    steps:
    - name: Get only last part of branch name in $SLUG_VERSION env var
      run:  |
        VERSION=${{ matrix.version }}
        echo "SLUG_VERSION=${VERSION//./-}" >> $GITHUB_ENV

    - name: Generate Github token for PR checks
      id: github-token-checks
      uses: actions/create-github-app-token@v1
      continue-on-error: true
      with:
        app-id: ${{ secrets.ALMA_UPDATE_CHECKS_APP_ID }}
        private-key: ${{ secrets.ALMA_UPDATE_CHECKS_APP_PEM }}
        repositories: alma-installments-prestashop

    - uses: LouisBrunner/checks-action@v2.0.0
      id: e2e_status
      with:
        token: ${{ steps.github-token-checks.outputs.token }}
        name: E2E Test / result (${{ matrix.version }})
        status: "in_progress"

    - name: Generate Github token for integration-infrastructure repo
      id: github-token-infrastructure
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.ALMA_WF_TRIGGER_APP_ID }}
        private-key: ${{ secrets.ALMA_WF_TRIGGER_APP_PEM }}
        repositories: integration-infrastructure

    - name: Invoke e2e workflow with inputs
      uses: benc-uk/workflow-dispatch@v1.2.3
      with:
        workflow: Deploy CMS
        token: ${{ steps.github-token-infrastructure.outputs.token }}
        repo: alma/integration-infrastructure
        ref: main
        inputs: >
          {
            "name": "e2e-${{ github.run_id }}",
            "alma_plugin_branch": "${{ github.head_ref || github.ref_name }}",
            "alma_plugin_test_branch" : "main",
            "cms": "prestashop-${{ matrix.version }}",
            "e2e": "true",
            "e2e_check_id": "${{ steps.e2e_status.outputs.check_id }}",
            "e2e_check_origin" : "${{ github.repository }}"
          }

    - uses: LouisBrunner/checks-action@v2.0.0
      if: failure()
      with:
        token: ${{ steps.github-token-checks.outputs.token }}
        check_id: ${{ steps.e2e_status.outputs.check_id }}
        conclusion: failure
